### ISSUE TITLE
Lower buttons are not styled on Mac

### ISSUE THREAD

**Issue by kvn1351** [Shirajuki/anki-redesign#42]
Hi, sorry for opening a new issue. There's one remaining thing not working as it should on mac. 

![CleanShot 2022-08-23 at 12 57 17](https://user-images.githubusercontent.com/11823348/186141547-dec8528f-8265-4c27-b9ba-d1d5c43d1e8b.png)

This is the reason:
![CleanShot 2022-08-23 at 12 58 48](https://user-images.githubusercontent.com/11823348/186141668-1d1a6efe-d01c-4e58-9177-3cbb28605563.png)

The styles are set as !important. And thus overwrite your styling.

**Comment by kvn1351** [comment]
Using !important as they have is completely unesseray and bad design. But well.

One easy "fix" is to use !important on everything too.

```css
/*BottomBar.css*/

body #outer button {
  color: var(--text-fg, var(--legacy-text-fg)) !important;
  border: none !important;
  border-radius: 15px !important;
  padding: 6px 24px !important;
  margin: 0 5px !important;
  cursor: pointer !important;
  font-weight: 500 !important;
  font-size: 0.875rem !important;
  line-height: 1.75 !important;
  letter-spacing: 0.02857em !important;
  text-transform: uppercase !important;
  min-width: 64px !important;
  background-color: var(--frame-bg, var(--legacy-frame-bg)) !important;
  transition: background 0.2s linear, color 0.3s ease-out !important;
  box-shadow: rgb(0 0 0 / 20%) 0px 3px 7px -2px,
    rgb(0 0 0 / 5%) 0px 5px 10px 0px, rgb(0 0 0 / 12%) 0px 1px 5px 0px !important;
}
body.nightMode #outer button {
  background: initial !important;
  background-color: var(--button-bg, var(--legacy-button-bg)) !important;
}

body #outer button:focus,
body #outer button.focus {
  background-color: var(--button-focus-bg, var(--legacy-button-focus-bg)) !important;
  color: var(--frame-bg, var(--legacy-frame-bg)) !important;
  outline: none !important;
}
body.nightMode #outer button:focus,
body.nightMode #outer button.focus {
  color: var(--text-fg, var(--legacy-text-fg)) !important;
}

body #outer button:hover {
  background-color: rgba(0, 0, 0, 0.05) !important;
}
body.nightMode #outer button:hover {
  background-color: rgba(255, 255, 255, 0.1) !important;
}
```

Another way would be to inject JS to remove these styles in the first place. This would be cleaner and adhere to good design practices I guess.
